apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-env
  creationTimestamp: null
data:
  .env: |-
    # define your env variables for the test env here
    KERNEL_CLASS='App\Kernel'
    APP_SECRET='asd'
    SYMFONY_DEPRECATIONS_HELPER=999999
    PANTHER_APP_ENV=panther
    PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots

    DB_NAME=atlas
    DB_USER=charlie
    DB_PASSWORD=123456

    MYSQL_DATABASE=${DB_NAME}
    MYSQL_USER=${DB_USER}
    MYSQL_PASSWORD=${DB_PASSWORD}
    MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?serverVersion=8.0

    ###> lexik/jwt-authentication-bundle ###
    JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
    JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
    JWT_PASSPHRASE=123456
    ###< lexik/jwt-authentication-bundle ###
    ###> symfony/framework-bundle ###
    APP_ENV=dev
    APP_SECRET=56c61f74a0d9ae867c8c3541d89ec046
    ###< symfony/framework-bundle ###

    ###> symfony/lock ###
    # Choose one of the stores below
    # postgresql+advisory://db_user:db_password@localhost/db_name
    LOCK_DSN=flock
    ###< symfony/lock ###

    APP_TIMEZONE=America/Sao_paulo
