FROM registry.digitalocean.com/charlie-container-registry/base:1.1

WORKDIR /var/www/html

COPY .infra/k8s/app/prod_custom_php.ini /usr/local/etc/php/conf.d/prod_custom_php.ini

COPY ./app /var/www/html

COPY .infra/k8s/nginx/nginx.conf /etc/nginx/nginx.conf
COPY .infra/k8s/nginx/sites /etc/nginx/sites-available
COPY .infra/k8s/nginx/conf.d /etc/nginx/conf.d
COPY .infra/k8s/nginx/startup.sh ./startup.sh

RUN mv .env.build .env

RUN chown -R www-data:www-data .

RUN composer install --no-scripts --optimize-autoloader

CMD [ "/bin/sh", "startup.sh" ]

EXPOSE 80

