apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.atlas.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.atlas.deployName }}
  ports:
  - protocol: {{ default "TCP" .Values.atlas.protocol }}
    port: {{ default "80" .Values.atlas.servicePort }}

  type: {{ default "ClusterIP" .Values.atlas.serviceType }}