apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.atlas.hpaName }}
  namespace: {{ .Values.global.namespace }}
spec:
  minReplicas: {{ .Values.atlas.minReplicas }}
  maxReplicas: {{ .Values.atlas.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.atlas.deployName }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.atlas.averageUtilization }}